### PR TITLE
Mongodb and MYSQL connection to Presto, Deploying Presto in EC2

### PR DESCRIPTION
**Pull request by ArpanRoy-Ahana**
The file added is a tutorial that describes how you can query a MongoDB container using docker-compose.

### CODE REVIEW

**Comment by ArpanRoy-Ahana** [comment]
@rohanpednekar  @alileclerc

**Review by tdcmeehan — CHANGES_REQUESTED** [review]
Please refer to other examples in this repository.  We want this information inline and in Markdown format.

**Comment by ArpanRoy-Ahana** [comment]
I will do that. Thanks @tdcmeehan .

**Comment by rohanpednekar** [comment]
please squash your updates into one commit.

**Pull request closed without merging**
