### PR TITLE
Rename docker-compose files to .yaml for consistency

### PR DESCRIPTION
**Pull request by Archy-X**
Renames the docker-compose-native files from .yml to .yaml to match the files in docker-compose for consistency.

### CODE REVIEW

**Comment by wanglinsong** [comment]
does this affect any other parts for the docs?

**Comment by wanglinsong** [comment]
Please use `yaml` instead of `yml`, according to official docs.
https://docs.docker.com/compose/compose-application-model/#:~:text=a%20distinct%20name.-,The%20Compose%20file,prefers%20the%20canonical%20compose.yaml%20

**Review by steveburnett — APPROVED** [review]
LGTM! (docs)

**Review by wanglinsong — APPROVED** [review]
LGTM

**Pull request merged**
